name: Build and Test .NET Application

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal     

    - name: Check test results and create Jira ticket on failure
      if: ${{ failure() }}
      run: |
        echo "Tests failed. Creating Jira ticket..."
        JIRA_URL="https://testjiragithubaction.atlassian.net/"
        USERNAME=${{ secrets.JIRA_USERNAME }}
        API_TOKEN=${{ secrets.JIRA_API_TOKEN }}
        curl -D- -u "$USERNAME:$API_TOKEN" -X POST --data "{
                                    \"fields\": {
                                      \"project\": {
                                        \"key\": \"SWAP\"
                                      },
                                      \"summary\": \"Automated GitHub Action Failure\",
                                      \"description\": \"Tests failed in GitHub Action workflow. See GitHub run [${{ github.run_number }}](${{ github.run_url }})\",
                                      \"issuetype\": {
                                        \"name\": \"Task\"
                                      }
                                    }
                                  }" -H "Content-Type: application/json" -v --url "$JIRA_URL/rest/api/2/issue"
      env:
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
      continue-on-error: true
